### ISSUE TITLE
Enforce HTTPS

### ISSUE THREAD

**Issue by konklone** [pawelmhm/pawelmhm.github.io#3]
GitHub now lets you enforce HTTPS for `*.github.io` domains:

https://github.com/blog/2186-https-for-github-pages

The site already works over HTTPS without errors: https://pawelmhm.github.io So this should be a trivial fix.

![support page](https://help.github.com/assets/images/help/pages/enforce-https-checkbox.png)

**Comment by pawelmhm** [comment]
:+1:  and done now, thanks @konklone

**Comment by konklone** [comment]
Thank you!
